### PR TITLE
Bug Fixes 

### PR DESCRIPTION
**Pull request by pasamyagnesh**
**Improvements include:**
1. Fixed flex layout issues in `index.html`.
2. Added `target="_blank"` so that documentation opens in a new tab.

Before:
Screenshot (6)
After:
Screenshot (5)

### CODE REVIEW

**Comment by pasamyagnesh** [comment]
Hey @harshithtunuguntla , @DCGUY009 . One check this PR.

**Comment by DCGUY009** [comment]
Hi @pasamyagnesh there are few more bugs pending with the app. Can you quickly check them and push them?

Bugs:
1. The Buttons in the Home Page are not consistent with the analytics page 
2. The main section where we have the input fields have glassmorphism design and in the analytics page it doesn't have it 
3. In the analytics page, the "Analytics button" is stretched out

image
image


I will be active here to accept it as soon as you are able to fix these and push them. Thanks!

**Comment by pasamyagnesh** [comment]
Ok @DCGUY009, I'll fix then

**Comment by DCGUY009** [comment]
Hi @pasamyagnesh 1 and half hour to go!

**Comment by DCGUY009** [comment]
Your PR has been accepted, thankyou for your active contribution to developing this Open Source Project. Hope you do great work ahead ✨

Happy Hacking 🚀

**Comment by pasamyagnesh** [comment]
Hey @DCGUY009 ,

Why changes are not reflecting ?is it for me?

Image from my local machine when server is running:[
Screenshot (266)
](url)

After merging the PR:
Screenshot (267)

**Comment by DCGUY009** [comment]
Hi @pasamyagnesh, try opening it in incognito once

**Comment by pasamyagnesh** [comment]
It's working

**Pull request merged**
