### PR TITLE
Postman API Documentation

### PR DESCRIPTION
**Pull request by pasamyagnesh**
**Overview:**
This PR implements comprehensive API documentation for Project OSUS, including detailed information for the `/analytics` and `/shorten` endpoints with sample request and responces. 

**Documentation Includes:**
- `/analytics` 
- `/shorten`

**Postman Collection:**
A Postman collection has been created for Project OSUS to facilitate easy testing of the API endpoints.

---

Images:

Screenshot (260)
Screenshot (261)

Screenshot (259)

### CODE REVIEW

**Comment by pasamyagnesh** [comment]
Hey @harshithtunuguntla and @DCGUY009,
Please let me know if you notice any errors or areas for improvement.

**Comment by Deepak-Perla** [comment]
Hey @pasamyagnesh,

We've checked your PR and found out some additions/fixes:
- The CSS has been altered, when you hover on the button it should change accordingly, which your PR does not align with the app.

  original:
  image
  your pr:
  image


- And an addition is that, you can add "new-tab" icon just beside the "API Docs" as it is redirecting to the new page.

new tab icon

Please make sure you pull the latest code before you make any changes, Happy Hacking 🚀

**Comment by pasamyagnesh** [comment]
Hey @Deepak-Perla,

Once check the changes.
1)  Added next tab icon icon  it will redirect to  API Docs
2) Fixed button hover in api.html

**Comment by harshithtunuguntla** [comment]
Approved the PR @pasamyagnesh ! Thanks for the contribution!

**Pull request merged**
