### PR TITLE
Fix issue #51

### PR DESCRIPTION
**Pull request by Sumit1911**
Check it

### CODE REVIEW

**Comment by Sumit1911** [comment]
Hi, @DCGUY009 
check now?

**Comment by DCGUY009** [comment]
Hi @Sumit1911 the functionality is alright, but I have a few suggestions from my side which would make it better:
1. Did you change the order of the buttons? They are in this order right now (Know More. Analytics/Home, Documentation) If you can maintain it this way in all the pages, it would be great! 
This is in analytics page: 
image
This is in home page:
image
This is the current website:



2. Inspect the website in a browser and click on "toggle device toolbar" to see how it is working. Specifically check at "627 X 678" pixels the "know more" button is not the same as the other 2 buttons. Again the order of the buttons do play a role here I believe. Think of something which works even if you have documentation button at this pixel points (627 x 678)
image

**Comment by Sumit1911** [comment]
Hi, @DCGUY009 
covered all the above mention functionalites, check it.

**Comment by DCGUY009** [comment]
Alright @Sumit1911 your PR has been merged. Happy Hacking 🚀

**Pull request merged**
