### PR TITLE
URL validation to automatically prepend 'https://' to links

### PR DESCRIPTION
**Pull request by vinayakchandra**
Automatically prepending `https://` to URLs entered without a protocol in the URL input field while keeping the input type = `URL`
#24

### CODE REVIEW

**Comment by harshithtunuguntla** [comment]
Hey @vinayakchandra ,

This is still not the ideal solution since the solution you've suggested is just appending the https:// to any input that is being shared. 

For example: if the user is just entering 'hello', it is just treating it as https://hello which is not an URL and the code is breaking while shortening the same.

The ideal solution should allow www. starting URLs, https:// starting URLs, http:// starting URLs while still maintaining the URL logic. 

Do pull the latest code and try implementing the same. Also, make sure you are registered for hacktoberfest to make every PR count as a part of open source contribution!

**Comment by DCGUY009** [comment]
Hi @vinayakchandra are you working on this or is it alright if we close this PR?

**Comment by DCGUY009** [comment]
Hi @vinayakchandra, we will be closing this in 24 hours, if you are working on it. Please reply here!

**Comment by DCGUY009** [comment]
Hey @vinayakchandra we are closing this as we have not recieved any response from you! If you want to work on this raise another PR. Happy Hacking ✨🚀

**Pull request closed without merging**
