### PR TITLE
Enhanced docs page with current theme

### LINKED ISSUE #61: [ENHANCEMENT] Documentation Page Consistency
## Description
There is a documentation page in the website but it is not consistent with the theme of the website. We don't have to change the whole page but at least look into making it more consistent with the main theme of the website!

## Benefits
This will make it more seamless for the users while interacting

## Improvements
1. We can change the header to make it look more like the home page and analytics page
2. Navigation to other pages from the documentation page is not present, we can add that 
3. The page icon for the browser tab is missing for the documentation page, the name in the documentation page could be "URL Shortener | Documentation" instead of "Project OSUS - Open Source URL Shortener"
image
image
4. A similar name change in Analytics page can also be made from "Analytics" to "URL Shortener | Analytics" to make the design consistent
image
5. Overall it looks like a separate page without any connection to the original website, we can work on making it consistent to the original website!

## Additional Context
image
image

### PR DESCRIPTION
**Pull request by devesh711**
# Closes #61

This pull request includes significant updates to the `templates/documentation.html` file, focusing on improving the overall design and user experience. The changes include enhancements to the visual styling, the addition of new elements, and updates to existing content.

### Visual and UX Improvements:

* Updated the overall color scheme to a dark theme and improved typography for better readability. (`templates/documentation.html`)
* Enhanced the header and footer sections with new styles, including a centered title and a call-to-action button in the header. (`templates/documentation.html`)
* Improved the sidebar with a new background color, box-shadow, and better spacing. (`templates/documentation.html`)
* Updated the main content area with a new background color, padding, and box-shadow for better visual separation. (`templates/documentation.html`)
* Added responsive design features to ensure the layout adapts well to different screen sizes. (`templates/documentation.html`)

### Content Updates:

* Reformatted the "Overview" section for better readability. (`templates/documentation.html`)
* Updated the "Installation" section with improved code block formatting. (`templates/documentation.html`)

## snapshots

image

### CODE REVIEW

**Comment by DCGUY009** [comment]
Hi @devesh711 the code change is cool! It blends more with the main website now.

But still as I mentioned in the main issue page, I think the header should be similar to the other pages in the website. 

Do you think otherwise, love to hear your thoughts on this😄

**Comment by devesh711** [comment]
yes I think there should be uniformity throughout the website. Let me See what i can do

**Comment by DCGUY009** [comment]
Hi @devesh711 great! Please do fetch the latest code from the repository before you work on your changes!

**Comment by DCGUY009** [comment]
Hi @devesh711 is there any update regarding this?

**Comment by DCGUY009** [comment]
Hi @devesh711 I don't see any changes implemented for this, we are merging this as this has been pending. You can raise another PR if you want with the changes!

**Comment by devesh711** [comment]
Fine

**Pull request merged**
