### PR TITLE
Implemented the link expiry feature.

### PR DESCRIPTION
**Pull request by pasamyagnesh**
### Description
This PR implements the link expiry feature utilizing the MongoDB TTL (Time To Live) concept. TTL indexes in MongoDB automatically remove documents from a collection after a specified amount of time or at a specific clock time. This feature ensures that links are managed efficiently, automatically expiring links that are no longer needed.

### Things to Do Before Testing This Code:

1. **Create a TTL Index**: You need to create a TTL index on the `expiration` field in your MongoDB collection to enable the automatic expiration of documents.

   **Mongo Shell Command to Create TTL Index**:
   ```javascript
   db.your_collection.createIndex({ expiration: 1 }, { expireAfterSeconds: 0 })
   
> **Note**:  
> - **Do not create a TTL index** if you want to maintain consistent data even after the link has expired.  
> - I designed the `@app.route('/<keyword>')` in a way that `errorpage.html` will display different error messages for various conditions.  
> 
> The current system handles two types of errors:
> 1. **Error 1**: When the keyword is not found in the database.
![keyword](https://github.com/user-attachments/assets/f3333b48-8929-41df-96a3-a9e805374893)

> 2. **Error 2**: When the URL has expired.  
![URL](https://github.com/user-attachments/assets/6ef18ead-8321-4b1e-b886-b68bce6f8073)

> 
> These error messages are properly handled and displayed to the user.



### Database Schema
After adding the `expiration` field, the updated database schema is as follows:

```json
{
    "keyword": "exampleKeyword",               
    "url": "https://example.com",             
    "clicks": 0,                              
    "created_at": "2024-10-23T21:53:00Z",     
    "expiration": "2024-10-30T21:53:00Z"       
}
```
- **keyword**: The unique identifier for the shortened link.
- **url**: The original long URL that is being shortened.
- **clicks**: A counter for tracking the number of accesses to the short URL.
- **created_at**: The timestamp when the link was created, in UTC.
- **expiration**: The date and time when the link will expire in UTC. If no expiration is set, this field will be `None`.

### New Features:

1. **Set time when the link has to expire:**
   sa

2. **Schedule link expiry notification:**
   rem

3. **Error message if the link has expired:**
   - If the link is accessed after the specified expiration time, it will no longer work. The system will display a message stating that the link has expired.

---

### Technical Details:

1. **Handling data in different time formats or time zones:**

   - When the data is created, it is converted and stored in the database in **UTC format** to maintain consistency.
   - While checking the remaining time to expire in the `/analytics` route, we convert both the current time and the scheduled expiration time into **Unix time** for efficient comparison.

   - **Packages used**: `pytz`
   - **Example of UTC time**: `2024-10-23T21:53:00Z`
   - **Example of Unix time**: `1724213564`
   
### Before changes:

[Screenshot (229)](url)  
[Screenshot (232)](url)

### After changes:

Screenshot (251)  
Screenshot (253)

### CODE REVIEW

**Comment by pasamyagnesh** [comment]
> ## Pull Request: Implemented Link Expiry Feature Using MongoDB TTL
> ### Description
> This PR implements the link expiry feature utilizing the MongoDB TTL (Time To Live) concept. TTL indexes in MongoDB automatically remove documents from a collection after a specified amount of time or at a specific clock time. This feature ensures that links are managed efficiently, automatically expiring links that are no longer needed.
> 
> ### Things to Do Before Testing This Code:
> 1. **Create a TTL Index**: You need to create a TTL index on the `expiration` field in your MongoDB collection to enable the automatic expiration of documents.
>    **Mongo Shell Command to Create TTL Index**:
>    ```js
>    db.your_collection.createIndex({ expiration: 1 }, { expireAfterSeconds: 0 })
>    ```
> 
> ### Database Schema
> After adding the `expiration` field, the updated database schema is as follows:
> 
> ```json
> {
>     "keyword": "exampleKeyword",               
>     "url": "https://example.com",             
>     "clicks": 0,                              
>     "created_at": "2024-10-23T21:53:00Z",     
>     "expiration": "2024-10-30T21:53:00Z"       
> }
> ```
> 
> * **keyword**: The unique identifier for the shortened link.
> * **url**: The original long URL that is being shortened.
> * **clicks**: A counter for tracking the number of accesses to the short URL.
> * **created_at**: The timestamp when the link was created, in UTC.
> * **expiration**: The date and time when the link will expire in UTC. If no expiration is set, this field will be `None`.
> 
> ### New Features:
> 1. **Set time when the link has to expire:**
>    sa
> 2. **Schedule link expiry notification:**
>    rem
> 3. **Error message if the link has expired:**
>    
>    * If the link is accessed after the specified expiration time, it will no longer work. The system will display a message stating that the link has expired.
> 
> ### Technical Details:
> 1. **Handling data in different time formats or time zones:**
>    
>    * When the data is created, it is converted and stored in the database in **UTC format** to maintain consistency.
>    * While checking the remaining time to expire in the `/analytics` route, we convert both the current time and the scheduled expiration time into **Unix time** for efficient comparison.
>    * **Packages used**: `pytz`
>    * **Example of UTC time**: `2024-10-23T21:53:00Z`
>    * **Example of Unix time**: `1724213564`
> 
> ## Images:
> ### Before changes:
> [Screenshot (229)](url) [Screenshot (232)](url)
> 
> ### After changes:
> Screenshot (251) Screenshot (253)

Hello @DCGUY009,
Once review this PR.

**Comment by pasamyagnesh** [comment]
Hey @DCGUY009 ,
Once review this PR

**Comment by NarayanaGudiwada** [comment]
@pasamyagnesh great work. But I think we should not remove the document it self when it's expired. we should do soft delete as I believe. we can later make use of that expired data as well in future. We can approve it and create new issue for this. Correct if I am wrong @DCGUY009

**Comment by pasamyagnesh** [comment]
Hey @DCGUY009,

Please take a moment to review the **Note** section that I recently updated before merging the code. I’ve added important details regarding the TTL index and error handling logic for expired links.

@NarayanaGudiwada, your feedback and insights would also be appreciated.

Thanks!

**Comment by DCGUY009** [comment]
Hi @pasamyagnesh we will review this and merge this by today if there are no issues!

**Comment by harshithtunuguntla** [comment]
Approved the PR @pasamyagnesh ! Thanks a lot for the contribution!!!

**Comment by harshithtunuguntla** [comment]
Also, You missed adding the library in requirements file.

**Pull request merged**
