### PR TITLE
changed the ui of the website

### PR DESCRIPTION
**Pull request by Bhumika-00**
as per the descripition the colour theme and responsive  has added to the website.
Screenshot from 2024-10-11 15-49-31
Screenshot from 2024-10-11 15-45-11
you can review it.

### CODE REVIEW

**Comment by Bhumika-00** [comment]
please authorize my pull request.

**Comment by Bhumika-00** [comment]
Thanks

**Comment by DCGUY009** [comment]
Thank you for your contribution, your PR has been accepted. 

But additionally please add these things into the UI as well:
-  In Mobile view instead of removing the documentation button, include a hamburger menu to include both the buttons
- Kindly raise a separate PR for the point mentioned above.

**Comment by Bhumika-00** [comment]
Okay

**Comment by Bhumika-00** [comment]
Please assign the label of level-1/level-2/level -3 I hope you justify my work with your label

**Pull request merged**
