### PR TITLE
Update index.html(for responswiveness)

### PR DESCRIPTION
**Pull request by Bhumika-00**
Instead of adding hamburger because it was not working when the size dec the buttons arranged in a column and logo gtoes at the bottom of screen.

### CODE REVIEW

**Comment by Bhumika-00** [comment]
the changes are made
Screenshot from 2024-10-12 17-38-07

**Comment by Bhumika-00** [comment]
biig screen
Screenshot from 2024-10-12 17-38-07

**Comment by DCGUY009** [comment]
Hi @Bhumika-00, I'm sorry but we can't merge this as this would make the UI Inconsistent across screens. The standard way of doing it is adding hamburger menu for buttons.

Can you tell us where exactly are you facing the issue with implementing the functionality of the Hamburger menu?

**Comment by Bhumika-00** [comment]
Okay no issues

**Pull request closed without merging**
