### PR TITLE
Added link preview feature

### PR DESCRIPTION
**Pull request by adarsh4k**
Users can now view a preview of the link they shorten which includes the title description and an image 
Features added:
Link preview display:
After a url is shortened the preview section shows key metadata including:
  1)Title of webpage
  2)providing a brief overview
  3)Image preview

### CODE REVIEW

**Comment by Deepak-Perla** [comment]
Hey @adarsh4k,

I hope you’re doing well! We wanted to discuss the recent changes you've made, especially regarding the fonts and styling. While it’s clear that there are significant updates, we believe it’s best to stick with the old UI.

However, we've encountered a few issues that we’d like to bring to your attention:

1. **Page Loading Issues**: Some pages aren't loaded, which affects the overall user experience although which were working in live. It would be helpful to solve which specific pages are causing this problem.

2. **Feature Functionality**: The feature you raised seems to be experiencing some difficulties. Could you clarify what the expected behavior is and what might be going wrong? If possible, could you attach some screenshots or photos from your local machine to illustrate these issues? Visuals will help us understand the context better.

 **It also seems that you might not have pulled the latest code from the main branch before making these changes. This could be contributing to some of the issues. Please pull the latest code from main branch.**

Thank you for your hard work on this! We appreciate your efforts, and I’m looking forward to resolving these points together.

Best,
Deepak.

**Comment by Deepak-Perla** [comment]
Hey @adarsh4k,

Today is the last day for submitting the PR for Hacktoberfest. Failing to do so hacktoberfest team will not count your PR and many not receive goodies.

**Comment by DCGUY009** [comment]
Hi @adarsh4k sorry we couldn't accept this PR. Hope you got something out of this Hacktober Fest 2024, happy hacking 🚀

**Comment by adarsh4k** [comment]
Hello @harshithtunuguntla anna
I wanted to express my gratitude for the opportunity to contribute to this project. Unfortunately, I was unable to submit a pull request yesterday due to an issue with my laptop display. However, working on this project has been an incredibly valuable learning experience, and I have gained so much insight into open source contribution.
Thank you once again for your support and guidance throughout this process.

**Pull request closed without merging**
