### PR TITLE
[Feature] QR code generation for shortened URLs

### PR DESCRIPTION
**Pull request by NarayanaGudiwada**
Issue - https://github.com/harshithtunuguntla/project-osus/issues/12
## Changes

- [x] Show qr code of shortened URL
- [x] Add Download qr code button

image

### CODE REVIEW

**Comment by NarayanaGudiwada** [comment]
Hi @DCGUY009  please review

**Comment by DCGUY009** [comment]
Hi @NarayanaGudiwada we will review this today and accept it by night if there are no issues!

**Comment by DCGUY009** [comment]
Hi @NarayanaGudiwada can you check why this is occuring and create a new PR?

**Comment by NarayanaGudiwada** [comment]
> Hi @NarayanaGudiwada can you check why this is occuring and create a new PR?

Hi @DCGUY009 I didn't get why it is occuring. I tested again in my local and it is working fine
image

**Comment by NarayanaGudiwada** [comment]
Seems like CSS changes are not reflected in the Image you pasted, can you check once

**Comment by DCGUY009** [comment]
Hi @NarayanaGudiwada it's working fine in local for me as well, but I'm not sure why it's not working when I merge it. Let me check again and in the meantime can you fetch the latest code and check again?

**Pull request merged**
